// <auto-generated />
namespace GridironGrub.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Restart : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Restart));
        
        string IMigrationMetadata.Id
        {
            get { return "201508291953282_Restart"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
